#555 Add nightly release of a snapshot
jenkinsci/kubernetes-operator pull request #566
Opened 2021-05-13 12:34 UTC by SylwiaBrant

GitHub Action that fires at 2:00 am UTC to build a snapshot image of the current repo and push it into DockerHub.

2021-05-13 13:07 UTC, prryb approved these changes

2021-05-17 10:04 UTC, KorusMateusz approved these changes

2021-05-17 10:24 UTC, tomaszsek requested changes

2021-05-17 10:24 UTC, tomaszsek commented on Makefile
> +	$(CONTAINER_RUNTIME_COMMAND) push $(DOCKER_ORGANIZATION)/$(DOCKER_REGISTRY):nightly-$(TAG) $(CONTAINER_RUNTIME_EXTRA_ARGS)
revert

2021-05-17 10:24 UTC, tomaszsek commented on .github/workflows/deploy-nightly.yaml
> +        run: echo "SHORTER_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
remove

2021-05-17 10:24 UTC, tomaszsek commented on .github/workflows/deploy-nightly.yaml
> +          make container-runtime-snapshot-push TAG=${{ env.SHORTER_SHA }}
```suggestion
          make container-runtime-snapshot-push
```

2021-05-17 10:24 UTC, tomaszsek commented on README.md
> +Look for the images with tag "nightly-{hash}", where {hash} is the hash of the master commit that interests you.
```suggestion
Look for the images with tag "{git-hash}", where {hash} is the hash of the master commit that interests you.
```

2021-05-24 10:13 UTC, merged

2021-05-24 10:13 UTC, tomaszsek approved these changes