Build multi-arch images
jenkinsci/kubernetes-operator pull request #693
Opened 2021-12-29 10:04 UTC by glebiller

# Changes

Changed Dockerfile & Makefile to build a multi-platform (amd64 and arm64) image of jenkins-operator.
Using `TARGETOS` and `TARGETARCH` in the builder and leverage `docker build build` command in the Makefile.

It is required to run `docker buildx create --use` before being able to create & push the image to registry.
Currently podman does not support buildx features, this changes requires `CONTAINER_RUNTIME_COMMAND=docker`.

# Release Notes

```
Support multi-arch (amd64 and arm64) container image.
```

2022-01-31 17:36 UTC, glebiller commented
I am still investigating why there is a timeout when running e2e tests.
It looks like the operator running cannot access minikube through its public IP 192.168.49.2 :(

2022-02-10 09:32 UTC, bhubert requested changes

2022-02-10 09:32 UTC, bhubert commented on Makefile
> +		--tag $(DOCKER_REGISTRY):$(GITCOMMIT) . \
you should add the plateform to the tag name, something like
--tag $(DOCKER_REGISTRY):$(GITCOMMIT)-$* . \

2022-02-11 22:10 UTC, glebiller commented
/assign @Sig00rd 
By bumping the Jenkins version & changing the default version of Plugins to match the one installed by a standard install, all the e2e are now passing correctly, in addition to building the ARM version of the image :)

2022-02-15 13:16 UTC, prryb approved these changes

2022-02-15 13:43 UTC, Sig00rd approved these changes

2022-02-15 13:51 UTC, Sig00rd commented
Thanks @glebiller, great work!

2022-02-15 13:51 UTC, merged